[package]
name = "misc"
version = "0.1.0"
edition = "2024"

[unstable]
build-std = ["alloc", "core"]

[dependencies]
rand = {  version = "0.8.5", default-features = false, features = ["small_rng"] }
psp = "0.3.11"
