[package]
name = "factory"
version = "0.1.0"
edition = "2021"

[unstable]
build-std = ["core", "alloc"]

[dependencies]
psp = "0.3.11"
psp-engine = { path="./psp-engine" }

[profile.release]
debug = true
